[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.0.1"
  export = ["echo_service_us"]
  icon = "docs/icon.png"
  keywords = ["Type/RestApi","Category/Service","Internal/http"]
  name = "echo_service_us"
  org = "yashodperera"
  version = "1.1.0"

